# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Настройте русскую версию сайта.
[ru]
  languageCode = "ru-ru"
  contentDir = "content/ru"
  title = "Дмитрий Власов"
  address = { street = "наб.реки Мойки 37А", city = "Санкт-Петербург", postcode = "191186", country = "Российская Федерация", country_code = "RU"}
  directions = "Вход со стороны реки Мойки. Подняться по лестнице. Перед стойкой охраны повернуть налево к лифтам. Подняться на пятый этаж. Пройти по коридору до конца на лево."
  office_hours = ["С понедельника по пятницу 10:00 to 19:00"]
  org_name = "Авара АйТи"
  description = "Заметки разработчика о жизни, Вселенной и всего такого."

  [[ru.menu.main]]
    name = "Обо мне"
    url = "#about"
    weight = 10

  [[ru.menu.main]]
    name = "Статьи"
    url = "#posts"
    weight = 20

  # [[ru.menu.main]]
  #   name = "Проекты"
  #   url = "#projects"
  #   weight = 30

  [[ru.menu.main]]
    name = "Выступления"
    url = "#talks"
    weight = 35

  [[ru.menu.main]]
    name = "Публикации"
    url = "#featured"
    weight = 40

# # Посмотреть подробнее как сделано:
  [[ru.menu.main]]
    name = "Курсы"
    url = "courses/"
    weight = 50

  [[ru.menu.main]]
    name = "Контакты"
    url = "#contact"
    weight = 60

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"
  title = "Dmitriy Vlasov"
  address = { street = "Moyka emb. 37A", city = "St.Petersburg", postcode = "191186", country = "Russia", country_code = "RU"}
  directions = "Entrance from the Moika river. Climb the stairs. In front of the security Desk, turn left to the elevators. Go up to the fifth floor. Go down the corridor to the end on the left."
  office_hours = ["Monday to Friday 10:00 AM to 07:00 PM"]
  org_name = "Awara IT"
  description = "BI developer's Notes on the life of the universe and all that."

  [[en.menu.main]]
    name = "Home"
    url = "#about"
    weight = 10

  [[en.menu.main]]
    name = "Posts"
    url = "#posts"
    weight = 20

  # [[en.menu.main]]
  #   name = "Projects"
  #   url = "#projects"
  #   weight = 30

  [[en.menu.main]]
    name = "Talks"
    url = "#talks"
    weight = 35

  [[en.menu.main]]
    name = "Publications"
    url = "#featured"
    weight = 40

# # Посмотреть подробнее как сделано:
#   [[en.menu.main]]
#     name = "Courses"
#     url = "courses/"
#     weight = 50

  [[en.menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 60
